const PRODUCTS = [
  {
    id: 1,
    name: "sdfsdf",
    description: "Experience crystal-clear sound with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and ultra-comfortable ear cushions for all-day listening.",
    base_price: 0,
    base_shipping_cost: 0,
    free_shipping: false,
    sku: "323424",
    slug: "sdfasdf",
    brand: "",
    rating: 4.7,
    reviews_count: 0,
    status: "active",
    isFeatured: false,
    isOnSale: false,
    requiresShipping: true,
    requiresInventoryTracking: true,
    stock: 15,
    hasVariants: false,
    totalVariantStock: 0,
    lowStockThreshold: 5,
    features: {
      0: "Active Noise Cancellation",
      1: "Bluetooth 5.0",
      2: "30-hour battery life",
      3: "Quick charge (5 min = 3 hours)",
      4: "Voice assistant compatible"
    },
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80"
    ],
    options: {},
    option_images: {},
    variant_images: {},
    option_variants_stock: {},
    option_price_adjustments: {},
    option_shipping_adjustments: {},
    weight: {
      value: 0,
      unit: "kg"
    },
    dimensions: {
      length: 0,
      width: 0,
      height: 0,
      unit: "cm"
    },
    option_dimension_overrides: {},
    categories: [],
    relatedProducts: [],
    createdAt: "2025-04-09T16:52:33.861Z",
    updatedAt: "2025-04-09T16:52:49.481Z",
    availability: "in_stock",
    backorderLimit: 0,
    category_ids: [],
    categoryId: 1,
    costPrice: 0,
    created_at: "2025-04-08T11:26:38.286Z",
    featured: false,
    inventory: {},
    metaDescription: "",
    new: false,
    onSale: false,
    price: 199.99,
    reviewCount: 0,
    sale: false,
    salePrice: null,
    taxClass: "standard",
    updated_at: "2025-04-08T11:26:38.286Z",
    upsellProducts: [],
    variants: [
      {
      id: "v1743605145464",
      sku: "VAR-1",
      name: "Premium Wireless Headphones Option 1",
      price: 199.99,
      salePrice: 0.06,
      stock: 4,
      attributes: {
      df: "f",
      asdf: "f"
    },
      weight: 333,
      dimensions: {
      length: 0.03,
      width: 0.03,
      height: 0.03,
      unit: "cm"
    }
    }
    ]
  },
  {
    id: 2,
    name: "Smart Fitness Tracker",
    description: "Track your health and fitness goals with our advanced smart fitness tracker. Monitor heart rate, sleep patterns, and activity levels with precision sensors and a vibrant display.",
    base_price: 0,
    base_shipping_cost: 0,
    free_shipping: false,
    sku: "PRD-002",
    slug: "smart-fitness-tracker",
    brand: "",
    rating: 4.5,
    reviews_count: 0,
    status: "active",
    isFeatured: false,
    isOnSale: false,
    requiresShipping: true,
    requiresInventoryTracking: true,
    stock: 42,
    hasVariants: false,
    totalVariantStock: 0,
    lowStockThreshold: 5,
    features: [
      "Heart rate monitoring",
      "Sleep tracking",
      "Water resistant (50m)",
      "7-day battery life",
      "Smartphone notifications"
    ],
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd6b0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1626371353531-b2cf4f8a4038?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80"
    ],
    options: {},
    option_images: {},
    variant_images: {},
    option_variants_stock: {},
    option_price_adjustments: {},
    option_shipping_adjustments: {},
    weight: {
      value: 0,
      unit: "kg"
    },
    dimensions: {
      length: 0,
      width: 0,
      height: 0,
      unit: "cm"
    },
    option_dimension_overrides: {},
    categories: [],
    relatedProducts: [],
    createdAt: "2025-04-09T16:52:33.861Z",
    updatedAt: "2025-04-09T16:52:33.861Z",
    availability: "in_stock",
    backorderLimit: 0,
    category_ids: [],
    categoryId: 1,
    costPrice: 0,
    created_at: "2025-04-08T11:26:38.286Z",
    featured: false,
    inventory: {},
    metaDescription: "",
    new: false,
    onSale: false,
    price: 89.99,
    reviewCount: 0,
    sale: false,
    salePrice: null,
    taxClass: "standard",
    updated_at: "2025-04-08T11:26:38.286Z",
    upsellProducts: [],
    variants: []
  },
  {
    id: 3,
    name: "Odio voluptatem Dolcasdfasdf asdf ",
    description: "Take your music anywhere with our compact yet powerful Bluetooth speaker. Featuring 360° sound, waterproof design, and 12 hours of playback for the perfect outdoor companion.",
    base_price: 0,
    base_shipping_cost: 0,
    free_shipping: false,
    sku: "Consequat Laboris a",
    slug: "Temporibus laboris e",
    brand: "",
    rating: 4.2,
    reviews_count: 0,
    status: "active",
    isFeatured: false,
    isOnSale: false,
    requiresShipping: true,
    requiresInventoryTracking: true,
    stock: 28,
    hasVariants: false,
    totalVariantStock: 0,
    lowStockThreshold: 5,
    features: [
      "Waterproof (IPX7)",
      "360° sound technology",
      "12-hour battery life",
      "Built-in microphone",
      "Portable design"
    ],
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1589003077984-894e133dabab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1596455607563-ad6193f76b17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80"
    ],
    options: {},
    option_images: {},
    variant_images: {},
    option_variants_stock: {},
    option_price_adjustments: {},
    option_shipping_adjustments: {},
    weight: {
      value: 0,
      unit: "kg"
    },
    dimensions: {
      length: 0,
      width: 0,
      height: 0,
      unit: "cm"
    },
    option_dimension_overrides: {},
    categories: [],
    relatedProducts: [],
    createdAt: "2025-04-09T16:52:33.861Z",
    updatedAt: "2025-04-09T16:52:33.861Z",
    availability: "in_stock",
    backorderLimit: 0,
    category_ids: [],
    categoryId: 1,
    costPrice: 0,
    created_at: "2025-04-08T11:26:38.286Z",
    featured: false,
    inventory: {},
    metaDescription: "",
    new: false,
    onSale: false,
    price: 59.99,
    reviewCount: 0,
    sale: false,
    salePrice: null,
    taxClass: "standard",
    updated_at: "2025-04-08T19:08:33.094Z",
    upsellProducts: [],
    variants: [
      {
      id: "v1743605125751",
      sku: "Sint ex temporibus a",
      name: "Sapiente tempora non",
      price: 37,
      salePrice: 88,
      stock: 98,
      attributes: {},
      weight: 46,
      dimensions: {
      length: 40,
      width: 97,
      height: 27,
      unit: "cm"
    }
    }
    ]
  }
];